// automatically generated by the FlatBuffers compiler, do not modify

package 

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type PutReq struct {
	_tab flatbuffers.Table
}

func GetRootAsPutReq(buf []byte, offset flatbuffers.UOffsetT) *PutReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PutReq{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PutReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PutReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *PutReq) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *PutReq) Blob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *PutReq) BlobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *PutReq) BlobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func PutReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func PutReqAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func PutReqAddBlob(builder *flatbuffers.Builder, blob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(blob), 0)
}
func PutReqStartBlobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func PutReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type PutRes struct {
	_tab flatbuffers.Table
}

func GetRootAsPutRes(buf []byte, offset flatbuffers.UOffsetT) *PutRes {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &PutRes{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *PutRes) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *PutRes) Table() flatbuffers.Table {
	return rcv._tab
}

func PutResStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func PutResEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type StreamReq struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamReq(buf []byte, offset flatbuffers.UOffsetT) *StreamReq {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamReq{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamReq) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamReq) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *StreamReq) Name() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *StreamReq) Blob(j int) byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		a := rcv._tab.Vector(o)
		return rcv._tab.GetByte(a + flatbuffers.UOffsetT(j*1))
	}
	return 0
}

func (rcv *StreamReq) BlobLength() int {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.VectorLen(o)
	}
	return 0
}

func (rcv *StreamReq) BlobBytes() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func StreamReqStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func StreamReqAddName(builder *flatbuffers.Builder, name flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(name), 0)
}
func StreamReqAddBlob(builder *flatbuffers.Builder, blob flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(blob), 0)
}
func StreamReqStartBlobVector(builder *flatbuffers.Builder, numElems int) flatbuffers.UOffsetT {
	return builder.StartVector(1, numElems, 1)
}
func StreamReqEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
type StreamRes struct {
	_tab flatbuffers.Table
}

func GetRootAsStreamRes(buf []byte, offset flatbuffers.UOffsetT) *StreamRes {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &StreamRes{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *StreamRes) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *StreamRes) Table() flatbuffers.Table {
	return rcv._tab
}

func StreamResStart(builder *flatbuffers.Builder) {
	builder.StartObject(0)
}
func StreamResEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
